Associate library-generated `description`, `hint` and `validationMessage` nodes with `aria-describedby`
segmentio/evergreen pull request #1324
Opened 2021-09-21 04:49 UTC by mxmason

Closes #1323.
## Overview
When an author provides `description`, `hint` and `validationMessage` values as strings, `evergreen-ui` now generates the right `aria-describedy` values to ensure that these messages are exposed to assistive technology.

⚠️ **Note:** Authors are still required to write their own `aria-describedby` relationships when they provide `description`, `hint` and `validationMessage` as JSX!

**Documentation**
- [x] Updated Typescript types and/or component PropTypes (unneeded in this PR)
- [ ] Added / modified component docs
- [ ] Added / modified Storybook stories

2021-10-06 15:07 UTC, zkuzmic requested changes
@mxmason this is a nice solution, thanks for opening the PR!

Just one change for you. Looks like there's a merge conflict as well.

2021-10-06 15:07 UTC, zkuzmic commented on src/select/src/SelectField.js
> +        aria-describedby={generateAriaDescribedBy(id, { description, hint, validationMessage })}
This `aria-describedby` isn't reaching the underlying `select` element. Instead, it's being placed on that element's wrapper.

I'd recommend changing the `Select` component to always pass `aria-describedby` down to the inner `select` element.

2021-10-06 16:36 UTC, mxmason commented
Thanks for catching my omission, @zkuzmic! I _think_ I fixed it; I will double-check in a few!

2022-06-14 19:20 UTC, zkuzmic approved these changes
LGTM 

(sorry for the months-long delay on this one 😅)

2022-06-14 19:29 UTC, merged